openapi: 3.0.0
info:
  version: '2.1.0'
  title: Sesame network security interface
  description: >-
    This document describes the interface of the Sesame which implements a
    service to provision network and endpoint security features
tags:
  - name: provisioning
paths: 
  #provisioning
  /nsus/provision/cas/{ca}/msisdns/{msisdn}/activate-ds:
    post:
      tags:
        - provisioning
      summary: Activate DNS security
      parameters:
        # header
        - $ref: '#/components/parameters/Msg_ctx_src'
        - $ref: '#/components/parameters/Msg_ctx_src_module'
        - $ref: '#/components/parameters/Msg_ctx_id'
        - $ref: '#/components/parameters/Msg_ctx_env'
        - $ref: '#/components/parameters/Msg_ctx_corr_id'
        - $ref: '#/components/parameters/Msg_ctx_user_id'
        #path
        - $ref: '#/components/parameters/ca'
        - $ref: '#/components/parameters/msisdn'
      responses:
        '204':
          description: Success
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-src-module:
              $ref: '#/components/headers/Msg_ctx_src_module'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
            msg-ctx-build-number:
              $ref: '#/components/headers/Msg_ctx_build_number'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  /nsus/provision/cas/{ca}/msisdns/{msisdn}/deactivate-ds:
    post:
      tags:
        - provisioning
      summary: Deactivate DNS security
      parameters:
        # header
        - $ref: '#/components/parameters/Msg_ctx_src'
        - $ref: '#/components/parameters/Msg_ctx_src_module'
        - $ref: '#/components/parameters/Msg_ctx_id'
        - $ref: '#/components/parameters/Msg_ctx_env'
        - $ref: '#/components/parameters/Msg_ctx_corr_id'
        - $ref: '#/components/parameters/Msg_ctx_user_id'
        #path
        - $ref: '#/components/parameters/ca'
        - $ref: '#/components/parameters/msisdn'
      responses:
        '204':
          description: Success
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-src-module:
              $ref: '#/components/headers/Msg_ctx_src_module'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
            msg-ctx-build-number:
              $ref: '#/components/headers/Msg_ctx_build_number'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  /nsus/provision/cas/{ca}/msisdns/{msisdn}/change-msisdn:
    post:
      tags:
        - provisioning
      summary: Change msisdn
      parameters:
        # header
        - $ref: '#/components/parameters/Msg_ctx_src'
        - $ref: '#/components/parameters/Msg_ctx_src_module'
        - $ref: '#/components/parameters/Msg_ctx_id'
        - $ref: '#/components/parameters/Msg_ctx_env'
        - $ref: '#/components/parameters/Msg_ctx_corr_id'
        - $ref: '#/components/parameters/Msg_ctx_user_id'
        #path
        - $ref: '#/components/parameters/ca'
        - $ref: '#/components/parameters/msisdn'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                new_msisdn:
                  $ref: '#/components/schemas/sMsisdn'
        description: New msisdn
      responses:
        '204':
          description: Success
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-src-module:
              $ref: '#/components/headers/Msg_ctx_src_module'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
            msg-ctx-build-number:
              $ref: '#/components/headers/Msg_ctx_build_number'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  /nsus/provision/cas/{ca}/msisdns/{msisdn}/move-msisdn:
    post:
      tags:
        - provisioning
      summary: Move msisdn
      parameters:
        # header
        - $ref: '#/components/parameters/Msg_ctx_src'
        - $ref: '#/components/parameters/Msg_ctx_src_module'
        - $ref: '#/components/parameters/Msg_ctx_id'
        - $ref: '#/components/parameters/Msg_ctx_env'
        - $ref: '#/components/parameters/Msg_ctx_corr_id'
        - $ref: '#/components/parameters/Msg_ctx_user_id'
        #path
        - $ref: '#/components/parameters/ca'
        - $ref: '#/components/parameters/msisdn'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                new_ca:
                  $ref: '#/components/schemas/nCa'
        description: New CA
      responses:
        '204':
          description: Success
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-src-module:
              $ref: '#/components/headers/Msg_ctx_src_module'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
            msg-ctx-build-number:
              $ref: '#/components/headers/Msg_ctx_build_number'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'

components:
  responses:
    '400':
      content:
        application/json:
          schema:
           $ref: '#/components/schemas/oErrorResponse'
          example: 
            error_code: 400
            error_description: Invalid msisdn format
      description: Bad request
      headers:
        msg-ctx-src:
          $ref: '#/components/headers/Msg_ctx_src'
        msg-ctx-src-module:
          $ref: '#/components/headers/Msg_ctx_src_module'
        msg-ctx-env:
          $ref: '#/components/headers/Msg_ctx_env'
        msg-ctx-id:
          $ref: '#/components/headers/Msg_ctx_id'
        msg-ctx-corr-id:
          $ref: '#/components/headers/Msg_ctx_corr_id'
        msg-ctx-build-number:
          $ref: '#/components/headers/Msg_ctx_build_number'
    '404':
      description: Returned if any entity was not found.
      headers:
        msg-ctx-src:
          $ref: '#/components/headers/Msg_ctx_src'
        msg-ctx-src-module:
          $ref: '#/components/headers/Msg_ctx_src_module'
        msg-ctx-env:
          $ref: '#/components/headers/Msg_ctx_env'
        msg-ctx-id:
          $ref: '#/components/headers/Msg_ctx_id'
        msg-ctx-corr-id:
          $ref: '#/components/headers/Msg_ctx_corr_id'
        msg-ctx-build-number:
          $ref: '#/components/headers/Msg_ctx_build_number'
      content:
        application/json:
          schema:
           $ref: '#/components/schemas/oErrorResponse'
          example: 
            error_code: 404
            error_description: Customer not found
    '500':
      content:
        application/json:
          schema:
           $ref: '#/components/schemas/oErrorResponse'
          example: 
            error_code: 500
            error_description: Internal server error
      description: Internal server error
      headers:
        msg-ctx-src:
          $ref: '#/components/headers/Msg_ctx_src'
        msg-ctx-src-module:
          $ref: '#/components/headers/Msg_ctx_src_module'
        msg-ctx-env:
          $ref: '#/components/headers/Msg_ctx_env'
        msg-ctx-id:
          $ref: '#/components/headers/Msg_ctx_id'
        msg-ctx-corr-id:
          $ref: '#/components/headers/Msg_ctx_corr_id'
        msg-ctx-build-number:
          $ref: '#/components/headers/Msg_ctx_build_number'
    '503':
      content:
        application/json:
          schema:
           $ref: '#/components/schemas/oErrorResponse'
          example: 
            error_code: 503
            error_description: Service is not available
      description: Server unavailable
      headers:
        msg-ctx-src:
          $ref: '#/components/headers/Msg_ctx_src'
        msg-ctx-src-module:
          $ref: '#/components/headers/Msg_ctx_src_module'
        msg-ctx-env:
          $ref: '#/components/headers/Msg_ctx_env'
        msg-ctx-id:
          $ref: '#/components/headers/Msg_ctx_id'
        msg-ctx-corr-id:
          $ref: '#/components/headers/Msg_ctx_corr_id'
        msg-ctx-build-number:
          $ref: '#/components/headers/Msg_ctx_build_number'
  headers:
    Location:
      description: (mandatory) The id of the newly created object
      required: true
      schema:
        type: string
        pattern: '^[0-9a-fA-F]{32}$'
        example: "43429a61f5f54ad4aec05a68d28b1350"
    Msg_ctx_src:
      description: (mandatory) Name of the source system, the sender party of the message. This is used primarily for gathering information on services usage. The name should contain a human-readable name of the application
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 64
        example: "LIGW"
    Msg_ctx_src_module:
      description: (optional) Name of the source system's module which sent the message. Fill only if suitable
      required: false
      schema:
        type: string
        minLength: 1
        maxLength: 64
        example: null
    Msg_ctx_env:
      description: (mandatory) Identifier of the environment. If the environment is production, use the value 'PROD'. Otherwise, use any string value which describes the environment (eg. 'UAT2')
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 32
        example: "PROD"
    Msg_ctx_id:
      description: (mandatory) Unique identifier of the message. The calling party must guarantee this being a unique identifier (UUID, GUID, etc.)
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 40
        example: "6b5fae5a-da07-4864-9683-ce55207d06af"
    Msg_ctx_corr_id:
      description: (mandatory) It intends to hold a flow (or session) identifier. The flow initiator generates the id, any other party should copy the received id into all subsequent messages/calls inside the flow. Ids should be unique for each and every flow
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 40
        example: "3385cbdb-8561-48f6-a671-5e271f486a41"
    Msg_ctx_build_number:
      description: (optional) It represents the sender application's build version
      required: false
      schema:
        type: string
        maxLength: 16
        example: "3.0.1"
  parameters:
    Msg_ctx_src:
      name: msg-ctx-src
      description: Name of the source system, the sender party of the message. This is used primarily for gathering information on services usage. The name should contain a human-readable name of the application
      in: header
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 64
        example: "INODE"
    Msg_ctx_src_module:
      name: msg-ctx-src-module
      description: Optional, name of the source system's module which sent the message. Fill only if suitable
      in: header
      required: false
      schema:
        type: string
        maxLength: 64
        example: "INode6 SIP AS"
    Msg_ctx_env:
      name: msg-ctx-env
      description: Identifier of the environment. If the environment is production, use the value 'PROD'. Otherwise, use any string value which describes the environment (eg. 'UAT2')
      in: header
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 32
        example: "PROD"
    Msg_ctx_id:
      name: msg-ctx-id
      description: Unique identifier of the message. The calling party must guarantee this being a unique identifier (UUID, GUID, etc.)
      in: header
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 40
        example: "53329a61-f5f5-4ad4-aec0-5a68d28b1350"
    Msg_ctx_corr_id:
      name: msg-ctx-corr-id
      description: It intends to hold a flow (or session) identifier. The flow initiator generates the id, any other party should copy the received id into all subsequent messages/calls inside the flow. Ids should be unique for each and every flow
      in: header
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 40
        example: "3385cbdb-8561-48f6-a671-5e271f486a41"
    Msg_ctx_build_number:
      name: msg-ctx-build-number
      description: It represents the sender application's build version
      in: header
      required: false
      schema:
        type: string
        maxLength: 16
        example: "6.0.1-pre"
    Msg_ctx_user_id:
      name: msg-ctx-user-id
      description: Optional value of the original user that initiated the action.
      in: header
      required: false
      schema:
        type: string
        maxLength: 64
        pattern: '^[a-zA-Z0-9-_.]+$'
        example: "oper"
    msisdn:
      name: msisdn
      in: path
      description: Affected msisdn. In case of ChangeMsisdn it is the old msisdn
      required: true
      schema:
        $ref: '#/components/schemas/sMsisdn'
    ca:
      name: ca
      in: path
      description: Affected CA. In case of MoveMsisdn it is the old CA
      required: true
      schema:
        $ref: '#/components/schemas/nCa'
  schemas:
    sMsisdn:
      description: User MSISDN
      type: string
      pattern: '36[0-9]{9}'
      example: '36201234567'
    nCa:
      description: CA
      type: number
      example: 36184912
    sMsgcntx_rrid:
      type: string
      minLength: 1
      maxLength: 40
    oErrorResponse:
      type: object
      properties:
          error_code:
            type: number
            minimum: 0
            description: Error code
            example: 2002
          error_description:
            type: string
            minLength: 0
            maxLength: 64
            description: Error description
            example: Retriable error