openapi: '3.0.2'
info:
  title: Sesame interfaces exposed to M2M Portal
  version: '1.2.0'
  description: |
    **v1.2.0**: Header standardization
servers:
  - url: https://sesame.m2m.pgsm.hu/
security:
  - x-api-key: []
paths:
  /m2msesame/v1/job/upload:
    post:
      tags:
          - Job operations
      summary: Initiate bulk job create
      parameters:
        - $ref: '#/components/parameters/msgcntx_src'
        - $ref: '#/components/parameters/msgcntx_id'
        - $ref: '#/components/parameters/msgcntx_env'
        - $ref: '#/components/parameters/msgcntx_corelid'
      requestBody:
        description: M2M Job list
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/JobList'
      responses:
        '200':
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/jobRequestResult'
          description: OK
        '400':
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
          content:
              application/json:
                schema:
                 $ref: '#/components/schemas/errorResponse'
                example: 
                  errorCode: 400
                  errorDescription: Invalid startTime format
          description: Bad request
        '401':
          description: Unauthorized 
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/errorResponse'
              example: 
                errorCode: 401
                errorDescription: Unauthorized
        '500':
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
          content:
              application/json:
                schema:
                 $ref: '#/components/schemas/errorResponse'
                example: 
                  errorCode: 500
                  errorDescription: Internal server error
          description: Internal server error
        '503':
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
          content:
              application/json:
                schema:
                 $ref: '#/components/schemas/errorResponse'
                example: 
                  errorCode: 503
                  errorDescription: Server is not available.
          description: Server unavailable
  /m2msesame/v1/job/delete:
    post:
      tags:
          - Job operations
      summary: Initiate bulk job delete
      parameters:
        - $ref: '#/components/parameters/msgcntx_src'
        - $ref: '#/components/parameters/msgcntx_id'
        - $ref: '#/components/parameters/msgcntx_env'
        - $ref: '#/components/parameters/msgcntx_corelid'
      requestBody:
        description: Job Transaction ids
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/JobDeleteList'
      responses:
        '200':
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/jobDeleteRequestResult'
          description: Deleted
        '400':
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
          content:
              application/json:
                schema:
                 $ref: '#/components/schemas/errorResponse'
                example: 
                  errorCode: 400
                  errorDescription: Invalid request data
          description: Bad request
        '401':
          description: Unauthorized 
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/errorResponse'
              example: 
                errorCode: 401
                errorDescription: Unauthorized
        '500':
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
          content:
              application/json:
                schema:
                 $ref: '#/components/schemas/errorResponse'
                example: 
                  errorCode: 500
                  errorDescription: Internal server error
          description: Internal server error
        '503':
          headers:
            msg-ctx-src:
              $ref: '#/components/headers/Msg_ctx_src'
            msg-ctx-env:
              $ref: '#/components/headers/Msg_ctx_env'
            msg-ctx-id:
              $ref: '#/components/headers/Msg_ctx_id'
            msg-ctx-corr-id:
              $ref: '#/components/headers/Msg_ctx_corr_id'
          content:
              application/json:
                schema:
                 $ref: '#/components/schemas/errorResponse'
                example: 
                  errorCode: 503
                  errorDescription: Server is not available
          description: Server unavailable
components:
  headers:
    Msg_ctx_src:
      description: (mandatory) Name of the source system, the sender party of the message. This is used primarily for gathering information on services usage. The name should contain a human-readable name of the application
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 64
        pattern: '^[a-zA-Z0-9-_]+$'
        example: "SESAME"
    Msg_ctx_env:
      description: (mandatory) Identifier of the environment. If the environment is production, use the value 'PROD'. Otherwise, use any string value which describes the environment (eg. 'UAT2')
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 32
        pattern: '^[a-z0-9-]+$'
        example: "prod"
    Msg_ctx_id:
      description: (mandatory) Unique identifier of the message. The calling party must guarantee this being a unique identifier (UUID, GUID, etc.)
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 40
        pattern: '^[0-9a-f]{16}$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        example: "6b5fae5a-da07-4864-9683-ce55207d06af"
    Msg_ctx_corr_id:
      description: (mandatory) It intends to hold a flow (or session) identifier. The flow initiator generates the id, any other party should copy the received id into all subsequent messages/calls inside the flow. Ids should be unique for each and every flow
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 40
        pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        example: "3385cbdb-8561-48f6-a671-5e271f486a41"
  parameters:
    msgcntx_src:
      name: msg-ctx-src
      description: Name of the source system, the sender party of the message. This is used primarily for gathering information on services usage. The name should contain a human-readable name of the application
      in: header
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 64
        pattern: '^[a-zA-Z0-9-_]+$'
        example: "SESAME"
    msgcntx_env:
      name: msg-ctx-env
      description: Identifier of the environment. If the environment is production, use the value 'PROD'. Otherwise, use any string value which describes the environment (eg. 'UAT2')
      in: header
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 32
        pattern: '^[a-z0-9-]+$'
        example: "prod"
    msgcntx_id:
      name: msg-ctx-id
      description: Unique identifier of the message. The calling party must guarantee this being a unique identifier (UUID, GUID, etc.)
      in: header
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 40
        pattern: '^[0-9a-f]{16}$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        example: "53329a61-f5f5-4ad4-aec0-5a68d28b1350"
    msgcntx_corelid:
      name: msg-ctx-corr-id
      description: It intends to hold a flow (or session) identifier. The flow initiator generates the id, any other party should copy the received id into all subsequent messages/calls inside the flow. Ids should be unique for each and every flow
      in: header
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 40
        pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        example: "3385cbdb-8561-48f6-a671-5e271f486a41"
  schemas:
    JobList:
      type: array
      description: Array of jobs
      items:
        $ref: '#/components/schemas/Job'
    Job:
      type: object
      required: [jobId,startTime]
      properties:
        jobId:
          type: string
          minLength: 1
          maxLength: 32
          description: M2M id of the job
          example: 1123
        type:
          type: string
          minLength: 1
          maxLength: 32
          description: Type of the job
          example: ROAMING
        startTime:
          type: string
          format: date-time
          description: Start time of the job
        ban:
          description: BAN
          type: number
          example: 36184912    
    JobDeleteList:
      type: array
      description: List of jobIds will be deleted
      items:
        properties:
          trxId:
            type: integer
            format: int64
            minimum: 1
            description: Sesame trx id
            example: 4000123211
    errorResponse:
      type: object
      properties:
          errorCode:
            type: number
            minimum: 0
            description: Error code
            example: 2002
          errorDescription:
            type: string
            minLength: 0
            maxLength: 64
            description: Error description
            example: Retriable error
    jobRequestResult:
      type: array
      description: List of job trx results 
      items:
        $ref: '#/components/schemas/singleJobResult'
    singleJobResult:
      type: object
      description: Result of a single job 
      properties:
        jobId:
          type: string
          minLength: 1
          maxLength: 32
          description: M2M id of the job
          example: 1123
        trxId:
            type: integer
            minimum: 1
            format: int64
            description: Sesame trx id
            example: 4000123211
        trxStatus:
          type: string
          description: Single trx status
          enum:
            - ACCEPTED
            - FAILED
            - INVALID
          example: ACCEPTED
    jobDeleteRequestResult:
      type: array
      description: List of delete job results 
      items:
        $ref: '#/components/schemas/singleJobDeleteResult'
    singleJobDeleteResult:
      type: object
      description: Result of a single delete job 
      properties:
        trxId:
            type: integer
            minimum: 1
            description: Sesame trx id
            example: 4000123211
        trxStatus:
          type: string
          description: Single delete status
          enum:
            - DELETED
            - FAILED
            - NOTFOUND
          example: DELETED
  securitySchemes:
    x-api-key:
      type: apiKey
      name: x-api-key
      in: header